[global]
developmentMode = false

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200
port = 8501

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#2EE6A6"
backgroundColor = "#0B1220"
secondaryBackgroundColor = "#121A2B"
textColor = "#FFFFFF"

[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true